- name: Harden Debian 12 with CIS Benchmark
  hosts: all
  become: yes

  vars:
    setup_audit: true
    run_audit: true
    audit_run_heavy_tests: true
    deb12cis_rule_5_2_4: false   # true: Ensure users must provide password for escalation
    deb12cis_rule_5_4_1_1: false # true: Ensure password expiration is configured
    deb12cis_rule_5_4_2_4: false # true: Ensure root password is set
    deb12cis_sshd:
      allow_users: "admin"
      allow_groups: "admin"
      client_alive_interval: 900
    deb12cis_ufw_allow_out_ports:
      - 53
      - 80
      - 443

  roles:
    - DEBIAN12-CIS
